base_config: ./config/din_dcn_config/
base_expid: DIN_DCN_default
dataset_id: MicroLens_1M_x1

dataset_config:
    MicroLens_1M_x1:
        data_root: ./data/
        data_format: parquet
        train_data: ./data/train.parquet
        valid_data: ./data/valid.parquet
        test_data: ./data/test.parquet
        item_info: ./data/item_info_updated.parquet
        rebuild_dataset: False
        feature_cols:
            - {name: user_id, active: True, dtype: int, type: meta}
            - {name: item_seq, active: True, dtype: int, type: meta}
            - {name: likes_level, active: True, dtype: int, type: categorical, vocab_size: 11}
            - {name: views_level, active: True, dtype: int, type: categorical, vocab_size: 11}
            - {name: item_id, active: True, dtype: int, type: categorical, vocab_size: 91718, source: item}
            - {name: item_tags, active: True, dtype: int, type: sequence, max_len: 5, vocab_size: 11740, source: item}
            - {name: item_emb_d128, active: True, dtype: float, type: embedding, source: item, embedding_dim: 128}
        label_col: {name: label, dtype: float}

tuner_space:
    embedding_regularizer: 1.e-6
    net_regularizer: 5.e-5
    net_dropout: 0
    learning_rate: 1.e-4
    batch_size: 512
    cross_layers: 6
